### ISSUE TITLE
Admin - Width of Select Boxes value not being saved.

### ISSUE THREAD

**Issue by albanycomputers** [backdrop-contrib/multiselect#5]
The admin settings to set the width of the widget is not being saved.

/admin/config/content/multiselect

**Comment by klonos** [comment]
FTR, while the default setting for the width is 230px, the help text in the field that holds this setting says 250px:
![image](https://user-images.githubusercontent.com/2423362/209513491-92c1ff79-eb80-4d3a-8c03-4b5e15666728.png)

Perhaps fix that along the way too? (only in the default config provided by the module I believe - no update hook, so not to mess with existing sites)

**Comment by klonos** [comment]
@albanycomputers here's a PR for review for when you have some time: https://github.com/backdrop-contrib/multiselect/pull/10/files

- fixed "no new line at end of file"
- corrected the value of `230` in the default config file to `250` (same as the help text for the field indicates) - not adding an update hook though, as we don't want to affect existing sites.
- changed the form field from a textfield to number instead, since we are saving number of pixels (that should provide some default validation as well)
- removed the `(in pixels)` from the field label, since we have the prefix in the field, + indicate that this is pixels in the help text.
- set the `'#min'` property of the form field to `10`, as I don't think that it makes sense to have it at `0` (no negative pixels) - is there any other sensible default that we should set this to?
- set the `'#max'` property to `9999` in order to allow for 4-digit values - in theory this number can have no limit, but if we omit setting a max value, then the field gets too wide.

Happy to tweak the PR according to feedback about min/max, or any other feedback for that matter.

**Comment by albanycomputers** [comment]
@klonos Many thanks...  I'll give it a play.

**Comment by herbdool** [comment]
@klonos I've tested and your PR works well.

**Comment by argiepiano** [comment]
I left a minor comment in the PR.

**Comment by albanycomputers** [comment]
Sorry @klonos , While I did test and it is working, I forgot to post a thank you in here :)
